### ISSUE TITLE
libxml2 (2.7.6) / zlib (1.2.5) versions incompatible

### ISSUE THREAD

**Issue by mutagene** [bfulgham/WinCairoRequirements#3]
I don't know if this issue manifests itself with wincairo WebKit builds, but the version of libxml2 here (2.7.6) does not appear to be compatible with the version of zlib (1.2.5).  Integrated into a larger project, were doing some XSL transforms which called xmlParserInputBufferCreateFilename, where the crashed occurred.

To make a long story short (or rather, to have someone else tell the story) - 

http://mail.gnome.org/archives/xml/2011-March/msg00039.html
http://git.gnome.org/browse/libxml2/commit/?id=a7e79f28689c574e0bbef17f4cb3da00249181ff

Updating libxml2 to 2.7.7 locally seems to have solved the problem.

**Comment by bfulgham** [comment]
Oh!  Thanks for catching this.  I'm updating the GitHub and WebKit
stuff this week, so I'll correct it.

Thanks!

-Brent

On Thu, Apr 12, 2012 at 7:45 PM, mutagene
reply@reply.github.com
wrote:

**Comment by bfulgham** [comment]
I just pushed an update that should resolve this.  Let me know if you encounter any further problems.
